In [1]:
import re
tesx='heloo, world this is test.'
result=re.split(r'(\s)',tesx)

In [2]:
result

['heloo,', ' ', 'world', ' ', 'this', ' ', 'is', ' ', 'test.']

In [3]:
result=[item for item in result if item.strip()]
result

['heloo,', 'world', 'this', 'is', 'test.']

In [8]:
text='heloo,world. is this  --a test?'
result=re.split(r'([,.:;?_!()\']|--|\s)',text)
result=[item.strip() for item in result if item.strip()]
result

['heloo', ',', 'world', '.', 'is', 'this', '--', 'a', 'test', '?']

In [9]:
result=[item for item in result if item.strip()]
result

['heloo', ',', 'world', '.', 'is', 'this', '--', 'a', 'test', '?']

In [18]:
with open(r"C:\Users\PC\Downloads\the-verdict.txt",'r',encoding='utf8') as f:
    row_text=f.read()
    print(row_text[:200])
    print(len(row_text))

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a
20479


In [29]:
preproses=re.split(r'([,.:;?_!()\']|--|\s)',row_text)
preproses=[item.strip() for item in preproses if item.strip()]
print(preproses[:20])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was']


In [32]:
all_words=sorted(set(preproses))
vocab_size=len(all_words)
print(vocab_size)
print(all_words[:20])

1158
['!', '"', '"Ah', '"Be', '"Begin', '"By', '"Come', '"Destroyed', '"Don', '"Gisburns"', '"Grindles', '"Hang', '"Has', '"How', '"I', '"If', '"It', '"Jack', '"Money', '"Moon-dancers"']


In [59]:
vocab={token:integer for integer,token in enumerate(all_words)}
#vocab

In [35]:
for i,item in enumerate(vocab.items()):
    print(item)
    if i>=50:
        break
        
    

('!', 0)
('"', 1)
('"Ah', 2)
('"Be', 3)
('"Begin', 4)
('"By', 5)
('"Come', 6)
('"Destroyed', 7)
('"Don', 8)
('"Gisburns"', 9)
('"Grindles', 10)
('"Hang', 11)
('"Has', 12)
('"How', 13)
('"I', 14)
('"If', 15)
('"It', 16)
('"Jack', 17)
('"Money', 18)
('"Moon-dancers"', 19)
('"Mr', 20)
('"Mrs', 21)
('"My', 22)
('"Never', 23)
('"Of', 24)
('"Oh', 25)
('"Once', 26)
('"Only', 27)
('"Or', 28)
('"That', 29)
('"The', 30)
('"Then', 31)
('"There', 32)
('"This', 33)
('"We', 34)
('"Well', 35)
('"What', 36)
('"When', 37)
('"Why', 38)
('"Yes', 39)
('"You', 40)
('"but', 41)
('"deadening', 42)
('"dragged', 43)
('"effects"', 44)
('"interesting"', 45)
('"lift', 46)
('"obituary"', 47)
('"strongest', 48)
('"strongly"', 49)
('"sweetly"', 50)


In [36]:
class simpletokenizer:
    def __init__(self,vocab):
        self.str_to_int=vocab
        self.int_to_str={i:s for s,i in vocab.items()}

    def encode(self,text):
        preproses=re.split(r'([,.:;?_!"()\"]|__|\s)',text)
        preproses=[
            item.strip() for item in preproses if item.strip()
            
        ]
        ids=[self.str_to_int[s] for s in preproses]
        return ids

    def decode(self,ids):
        text=" ".join([self.int_to_str[i] for i in ids])
        #replace space before the specifield punctuations
        text=re.sub(r'([,.:;?_!"()\"]|__|\s)',r'\1',text)
        return text

In [41]:
tokenizer=simpletokenizer(vocab)
text='I HAD always thought Jack Gisburn rather '
ids=tokenizer.encode(text)
print(ids)

[92, 86, 181, 1030, 96, 82, 848]


In [42]:
tokenizer.decode(ids)

'I HAD always thought Jack Gisburn rather'

In [57]:
# adding specail context tokens
tokenizer.encode('I have now man ')

[92, 561, 745, 687]

# creting inpu target pairs

In [5]:
import tiktoken 
tokenizer=tiktoken.encoding_for_model('gpt-4o')

In [9]:
enc_text=tokenizer.encode(row_text)
enc_text[:10]

[40, 148954, 3324, 4525, 10874, 165003, 33750, 7542, 261, 12424]

# token embedding

In [1]:
import gensim.downloader as api
model=api.load('glove-twitter-25')

In [2]:
word_vector=model

In [3]:
print(word_vector['king'])

[-0.74501  -0.11992   0.37329   0.36847  -0.4472   -0.2288    0.70118
  0.82872   0.39486  -0.58347   0.41488   0.37074  -3.6906   -0.20101
  0.11472  -0.34661   0.36208   0.095679 -0.01765   0.68498  -0.049013
  0.54049  -0.21005  -0.65397   0.64556 ]


In [6]:
print(word_vector.most_similar(positive=('king'+'woman'),negative=('man')))

KeyError: "Key 'kingwoman' not present in vocabulary"

In [10]:
print(word_vector.most_similar('king'))

[('prince', 0.93374103307724), ('queen', 0.920242190361023), ('aka', 0.9176923036575317), ('lady', 0.9163240790367126), ('jack', 0.9147355556488037), ("'s", 0.9066898226737976), ('stone', 0.8982375264167786), ('mr.', 0.8919408321380615), ('the', 0.889343798160553), ('star', 0.8892088532447815)]


In [ ]:
embedding layers is loop opration that retrive rows from embedding layers weight matrix 

In [1]:
import torch
vocab_size=6
dim=3

In [2]:
embedding_layers=torch.nn.Embedding(vocab_size,dim)
embedding_layers.weight

Parameter containing:
tensor([[ 0.6151,  0.0304, -0.1982],
        [ 1.2982,  0.8404,  2.0460],
        [-0.9998, -0.0073, -0.4177],
        [ 0.0121,  3.0166, -0.3100],
        [ 0.2235,  0.2551,  0.0493],
        [-0.3765, -1.2246,  1.2819]], requires_grad=True)

In [6]:
print(embedding_layers(torch.tensor([3])))

tensor([[ 0.0121,  3.0166, -0.3100]], grad_fn=<EmbeddingBackward0>)


In [7]:
input_id=torch.tensor([1,3,4,2])

In [8]:
print(embedding_layers(input_id
                      ))

tensor([[ 1.2982,  0.8404,  2.0460],
        [ 0.0121,  3.0166, -0.3100],
        [ 0.2235,  0.2551,  0.0493],
        [-0.9998, -0.0073, -0.4177]], grad_fn=<EmbeddingBackward0>)


# positional embedding

In [15]:
vocab_size=50257
out_dim=256
token_embedding_layer=torch.nn.Embedding(vocab_size,out_dim)
token_embedding_layer.weight

Parameter containing:
tensor([[ 1.3659,  0.6687, -0.0863,  ..., -0.1810,  1.5025,  0.1384],
        [ 0.2432, -1.1451, -0.0137,  ..., -0.1045, -0.5061, -0.6426],
        [-0.2901, -0.3078, -0.0566,  ...,  1.0661,  1.6659, -1.1912],
        ...,
        [ 0.6486, -0.5554,  1.2554,  ...,  1.2428,  0.0530, -0.5169],
        [ 0.2236, -0.0877, -1.0494,  ...,  1.3145, -0.0686,  0.7431],
        [-1.0457,  0.3270,  1.2243,  ..., -1.9333, -0.5221, -0.4361]],
       requires_grad=True)

In [16]:
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [21]:
import tiktoken

In [22]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [23]:
dataloader = create_dataloader_v1(row_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [25]:
token_embedding=token_embedding_layer(inputs)
token_embedding.shape

torch.Size([8, 4, 256])

In [28]:
max_length=4
context_lenght=max_length
pos_embedding_layer=torch.nn.Embedding(max_length,out_dim)
pos_emmbeding=pos_embedding_layer(torch.arange(max_length))
pos_emmbeding.shape


torch.Size([4, 256])

In [32]:
input_embedding=token_embedding+pos_emmbeding
input_embedding.shape
# ye jayega final gpt blocks me
input_embedding[3]

tensor([[-1.8454, -1.2769, -0.3401,  ..., -1.0992,  1.9158, -1.2032],
        [-1.8999,  3.1460,  0.3904,  ...,  0.3011, -2.9683,  0.3025],
        [-1.5132, -2.2257, -1.7497,  ..., -0.7314,  1.2589,  1.5244],
        [ 0.1837, -2.1983,  1.8922,  ...,  0.7748,  1.7022, -1.2920]],
       grad_fn=<SelectBackward0>)

In [26]:
print(torch.arange(20))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [ ]:
#